### ISSUE TITLE
Publish jars on artifact repository (Bintray shutdown)

### ISSUE THREAD

**Issue by theborakompanioni** [ConsensusJ/consensusj#71]
First off: You are boosting so many devs productivity - single-handedly.  Big thank you for publishing and maintaining (!) this  library. 

Are there already any plans on publishing the artifacts somewhere else than Bintray?
Bintray itself will be shutting down on May 1st and I already see 403 Forbidden when accessing some packages.

> All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021.

Since it seems you own "msgilligan.com" Maven Central might be an alternative.
Also https://jitpack.io/#ConsensusJ/consensusj with signed packages might be an alternative.

What are your thoughts on this topic?

Read more: https://blog.gradle.org/jcenter-shutdown

edit: added link to gradle blog about jcenter shutdown
edit2: 403 Forbidden is probably caused by the "brown-out session" ("Schedule brown-out session on April 12th 6AM to 2PM Pacific Daylight Time" on https://status.bintray.com/) - artifact download should be working till February 1st 2022.

**Comment by msgilligan** [comment]
Hi @theborakompanioni, thanks for the feedback!

Yes, I plan on eventually publishing to Maven Central. Hopefully long before Feb 1st 2022. The next release of ConsensusJ (v0.5.8 or v0.6.0) will need to be published somewhere besides BinTray -- since BinTray doesn't allow new releases. It will probably be either Github, Gitlab, or maybe an S3-based repo. I need to do a bit of additional cleanup before publishing to Maven Central, but hope to get that done in the coming months.

**Comment by theborakompanioni** [comment]
@msgilligan That's great news. I guess it is rather low priority since it is enough time. Thank you!

**Comment by msgilligan** [comment]
Actually, private BinTray repos, like the one for ConsensusJ have been deactivated. 

Current snapshots are being published to [Gitlab](https://gitlab.com/ConsensusJ/consensusj/-/packages).

**Comment by msgilligan** [comment]
Release 0.5.8 has been published to a public Maven repo on Git**Lab**.

The README has been updated to show how to reference that repo: https://github.com/ConsensusJ/consensusj#binaries

**Comment by msgilligan** [comment]
I'm closing this issue as resolved and opening Issue #72 for publishing to Maven Central.
